import { test } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, statSync, utimesSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import yaml from 'js-yaml';
import { main } from '../index.js';

// `kanso discover`, with the click-through stood in: what the command makes of
// what was found — printed, or written whole as .kanso/states.yml, with the
// project's own .kanso.yml left as it was. The click-through itself is tested against a real Chrome
// (test/discover/).

function fakeIo() {
  const io = { out: '', err: '' };
  io.stdout = { write: (s) => { io.out += s; } };
  io.stderr = { write: (s) => { io.err += s; } };
  return io;
}

function project(kansoYml) {
  const cwd = mkdtempSync(join(tmpdir(), 'kanso-discover-'));
  if (kansoYml != null) writeFileSync(join(cwd, '.kanso.yml'), kansoYml);
  return cwd;
}

// A menu on both screens, a sign-up form inside it, and a drawer only the
// phone's layout has.
const FOUND = {
  explored: {
    mobile: [
      { id: 1, parent: null, click: '#menu', waitFor: '#menu[aria-expanded="true"]', role: 'button', name: 'Menu', depth: 1 },
      { id: 2, parent: 1, click: '#signup', waitFor: null, role: 'link', name: 'Sign up', depth: 2 },
      { id: 3, parent: null, click: '#burger', waitFor: '#drawer', role: 'button', name: 'Open navigation', depth: 1 },
    ],
    desktop: [
      { id: 1, parent: null, click: '#menu', waitFor: '#menu[aria-expanded="true"]', role: 'button', name: 'Menu', depth: 1 },
      { id: 2, parent: 1, click: '#signup', waitFor: null, role: 'link', name: 'Sign up', depth: 2 },
    ],
  },
  dropped: [{ formFactor: 'desktop', id: 4, parent: null, click: '#flaky', role: 'button', name: 'Flaky', reason: 'nothing visible to click at #flaky' }],
  runs: {
    mobile: { clicks: 12, stable: true, leftInQueue: 0, outOfTime: false },
    desktop: { clicks: 9, stable: true, leftInQueue: 0, outOfTime: false },
  },
};

function fakeDiscover(found = FOUND) {
  const calls = [];
  const discover = async (url, opts) => {
    calls.push({ url, ...opts });
    return found;
  };
  discover.calls = calls;
  return discover;
}

async function run(argv, { cwd = project(), discover = fakeDiscover() } = {}) {
  const io = fakeIo();
  const code = await main(argv, { io, cwd, discover });
  return { code, cwd, ...io };
}

const stateNamesIn = (text) => {
  const names = [];
  const walk = (states) => states?.forEach((state) => { names.push(state.name); walk(state.states); });
  walk(yaml.load(text).states);
  return names;
};

const generated = (cwd) => join(cwd, '.kanso', 'states.yml');

test('discover prints the file it would write, and writes nothing', async () => {
  const cwd = project();
  const { code, out, err } = await run(['discover', 'http://localhost:3000'], { cwd });

  assert.equal(code, 0);
  assert.match(out, /^# Generated by `kanso discover`/);
  const { states } = yaml.load(out);
  assert.deepEqual(states, [
    { name: 'menu', click: '#menu', wait_for: '#menu[aria-expanded="true"]', states: [{ name: 'sign-up', click: '#signup' }] },
    { name: 'open-navigation', form_factor: 'mobile', click: '#burger', wait_for: '#drawer' },
  ]);
  assert.match(err, /mobile: 3 states from 12 clicks/);
  assert.match(err, /left out on desktop: button "Flaky" — it did not replay/);
  assert.match(err, /3 states found/);
  assert.match(err, /^an audit through these states takes about a minute, roughly — twice that against a baseline$/m);
  assert.match(err, /--write to write them to \.kanso\/states\.yml/);
  assert.equal(existsSync(join(cwd, '.kanso')), false);
  assert.equal(existsSync(join(cwd, '.kanso.yml')), false);
});

test('the clicks left out because the guards stopped something are counted, with what was stopped, once each', async () => {
  const guarded = [
    { role: 'button', name: 'Tip 2 €', stopped: ['POST /api/payment/tip'] },
    { role: 'button', name: 'Tip 5 €', stopped: ['POST /api/payment/tip'] },
    { role: 'button', name: 'Clear all', stopped: ['confirm'] },
  ];
  const found = { ...FOUND, runs: { ...FOUND.runs, mobile: { ...FOUND.runs.mobile, guarded }, desktop: { ...FOUND.runs.desktop, guarded: guarded.slice(2) } } };
  const { err } = await run(['discover', 'http://localhost:3000'], { discover: fakeDiscover(found) });

  assert.match(err, /^mobile: 3 states from 12 clicks, 3 clicks not kept: they write, leave or ask \(POST \/api\/payment\/tip, confirm\)$/m);
  assert.match(err, /^desktop: 2 states from 9 clicks, 1 click not kept: it writes, leaves or asks \(confirm\)$/m);
});

test('a run whose guards stopped nothing says nothing of them', async () => {
  const found = { ...FOUND, runs: { ...FOUND.runs, mobile: { ...FOUND.runs.mobile, guarded: [] } } };
  const { err } = await run(['discover', 'http://localhost:3000'], { discover: fakeDiscover(found) });
  assert.match(err, /^mobile: 3 states from 12 clicks$/m);
  assert.doesNotMatch(err, /not kept/);
});

test('--write writes the file whole under .kanso/, and leaves .kanso.yml byte for byte as it was', async () => {
  const kansoYml = '# the budgets we agreed on\nbudgets:\n  mobile:\n    lcp: 2500\nstates:\n  - name: nav\n    click: "#menu"\n    close: "#menu-close"\n';
  const cwd = project(kansoYml);
  const printed = (await run(['discover', 'http://localhost:3000'], { cwd })).out;
  const { code, out, err } = await run(['discover', 'http://localhost:3000', '--write'], { cwd });

  assert.equal(code, 0);
  assert.equal(out, '');
  assert.equal(readFileSync(generated(cwd), 'utf8'), printed);
  assert.equal(readFileSync(join(cwd, '.kanso.yml'), 'utf8'), kansoYml);
  assert.match(err, /wrote \.kanso\/states\.yml\n {2}added: menu, sign-up, open-navigation\n/);
});

test('with no .kanso.yml, the file is written in the working directory', async () => {
  const cwd = project();
  await run(['discover', 'http://localhost:3000', '--write'], { cwd });
  assert.deepEqual(yaml.load(readFileSync(generated(cwd), 'utf8')).states.map(({ name }) => name), ['menu', 'open-navigation']);
  assert.equal(existsSync(join(cwd, '.kanso.yml')), false);
});

test('a configuration named elsewhere has its generated file beside it', async () => {
  const cwd = project();
  mkdirSync(join(cwd, 'config'));
  writeFileSync(join(cwd, 'config', 'kanso.yml'), 'runs: 1\n');
  const { err } = await run(['discover', 'http://localhost:3000', '--write', '--config', 'config/kanso.yml'], { cwd });
  assert.ok(existsSync(join(cwd, 'config', '.kanso', 'states.yml')));
  assert.match(err, /wrote config\/\.kanso\/states\.yml/);
});

test('a second run that finds the same says the file is unchanged, and leaves it be', async () => {
  const cwd = project();
  await run(['discover', 'http://localhost:3000', '--write'], { cwd });
  const path = generated(cwd);
  const past = new Date(Math.floor(Date.now() / 1000) * 1000 - 60_000);
  utimesSync(path, past, past);
  const { err } = await run(['discover', 'http://localhost:3000', '--write'], { cwd });

  assert.match(err, /\.kanso\/states\.yml unchanged/);
  assert.equal(Math.round(statSync(path).mtimeMs), past.getTime());
});

test('a run that finds something else rewrites the file, naming what it added and what it removed', async () => {
  const cwd = project();
  await run(['discover', 'http://localhost:3000', '--write'], { cwd });
  const settings = { id: 5, parent: null, click: '#settings', waitFor: null, role: 'button', name: 'Settings', depth: 1 };
  const found = { ...FOUND, explored: { mobile: [FOUND.explored.mobile[0], settings], desktop: [FOUND.explored.desktop[0], settings] } };
  const { err } = await run(['discover', 'http://localhost:3000', '--write'], { cwd, discover: fakeDiscover(found) });

  assert.match(err, /added: settings\n/);
  assert.match(err, /removed: sign-up, open-navigation\n/);
  const text = readFileSync(generated(cwd), 'utf8');
  assert.equal(text.includes('sign-up'), false);
  assert.deepEqual(yaml.load(text).states.map(({ name }) => name), ['menu', 'settings']);
});

test('a name a hand-written state takes is not given to a found one', async () => {
  const cwd = project('states:\n  - name: menu\n    click: "#other"\n');
  const { out } = await run(['discover', 'http://localhost:3000'], { cwd });
  assert.deepEqual(yaml.load(out).states.map(({ name }) => name), ['menu-2', 'open-navigation']);
});

// Its own earlier names are the file's to hand out again: what it wrote last
// time is replaced, not kept beside.
test('the names the generated file already holds are not taken from the next run', async () => {
  const cwd = project();
  await run(['discover', 'http://localhost:3000', '--write'], { cwd });
  const { out } = await run(['discover', 'http://localhost:3000'], { cwd });
  assert.deepEqual(yaml.load(out).states.map(({ name }) => name), ['menu', 'open-navigation']);
});

test('nothing found is still a file, which says so', async () => {
  const cwd = project();
  const found = { ...FOUND, explored: { mobile: [], desktop: [] }, dropped: [] };
  const { err } = await run(['discover', 'http://localhost:3000', '--write'], { cwd, discover: fakeDiscover(found) });
  assert.match(err, /0 states found/);
  assert.deepEqual(yaml.load(readFileSync(generated(cwd), 'utf8')), { states: [] });
});

test('the depth, the clicks and the screen are handed to the click-through', async () => {
  const discover = fakeDiscover();
  await run(['discover', 'http://localhost:3000', '--depth', '1', '--max-clicks', '20', '--form-factor', 'mobile'], { discover });

  assert.deepEqual(discover.calls.map(({ url, maxDepth, maxClicks, formFactors }) => ({ url, maxDepth, maxClicks, formFactors })), [
    { url: 'http://localhost:3000/', maxDepth: 1, maxClicks: 20, formFactors: ['mobile'] },
  ]);
});

// Many top-level states, and one reached from the first: breadth first, the
// child is the first to go.
function many(count) {
  const mobile = Array.from({ length: count }, (_, i) => ({ id: i + 1, parent: null, click: `#s${i + 1}`, waitFor: null, role: 'button', name: `State number ${i + 1}`, depth: 1 }));
  mobile.push({ id: 100, parent: 1, click: '#deep', waitFor: null, role: 'link', name: 'Deep link', depth: 2 });
  return { ...FOUND, explored: { mobile, desktop: mobile }, dropped: [] };
}

test('at most twenty states are written unless told otherwise, and the summary names the first left out', async () => {
  const { out, err } = await run(['discover', 'http://localhost:3000'], { discover: fakeDiscover(many(24)) });
  const names = stateNamesIn(out);
  assert.equal(names.length, 20);
  assert.equal(names.at(-1), 'state-number-20');
  assert.match(err, /^25 states found, 20 kept: 5 over --max-states 20 left out, the last found \(button "State number 21", button "State number 22", button "State number 23", button "State number 24", …\)$/m);
  assert.match(err, /takes about 5 min, roughly/);
});

test('--max-states sets the cap, and an audit through fewer states is said to take less', async () => {
  const { out, err } = await run(['discover', 'http://localhost:3000', '--max-states', '8'], { discover: fakeDiscover(many(24)) });
  assert.equal(stateNamesIn(out).length, 8);
  assert.match(err, /25 states found, 8 kept: 17 over --max-states 8 left out/);
  assert.match(err, /takes about 2 min, roughly/);

  const all = await run(['discover', 'http://localhost:3000', '--max-states', '30'], { discover: fakeDiscover(many(24)) });
  assert.equal(stateNamesIn(all.out).length, 25);
  assert.match(all.err, /^25 states found$/m);
  assert.match(all.err, /takes about 7 min, roughly/);
});

test('the estimate counts the states the project wrote by hand as well', async () => {
  const cwd = project('states:\n  - name: nav\n    click: "#nav"\n  - name: help\n    click: "#help"\n');
  const { err } = await run(['discover', 'http://localhost:3000'], { cwd });
  // Three found on mobile and two of the project's: 15 s + 5 × 15 s.
  assert.match(err, /^an audit through these states and the 2 of \.kanso\.yml takes about 2 min, roughly/m);
});

test('--json says how many states it keeps at most, which it left out, and about how long an audit takes', async () => {
  const { out } = await run(['discover', 'http://localhost:3000', '--json', '--max-states', '23'], { discover: fakeDiscover(many(24)) });
  const result = JSON.parse(out);
  assert.equal(result.maxStates, 23);
  assert.deepEqual(result.leftOut.map(({ name, depth }) => [name, depth]), [['State number 24', 1], ['Deep link', 2]]);
  assert.equal(result.auditSeconds, 15 + 15 * 23);
});

test('--json prints what was found, the tree and where it goes, and nothing else', async () => {
  const cwd = project();
  const { out, err } = await run(['discover', 'http://localhost:3000', '--json'], { cwd });
  const result = JSON.parse(out);
  assert.deepEqual(result.states.map(({ name }) => name), ['menu', 'open-navigation']);
  assert.deepEqual(result.states[0].states.map(({ name }) => name), ['sign-up']);
  assert.equal(result.statesFile, generated(cwd));
  assert.deepEqual(result.runs, FOUND.runs);
  assert.equal(err, '');
  assert.equal(existsSync(join(cwd, '.kanso')), false);
});

test('--json with --write writes the file and prints only the JSON', async () => {
  const cwd = project();
  const { out, err } = await run(['discover', 'http://localhost:3000', '--json', '--write'], { cwd });
  assert.equal(JSON.parse(out).statesFile, generated(cwd));
  assert.equal(err, '');
  assert.ok(existsSync(generated(cwd)));
});

test('an audit option on discover, or a discover option on an audit, is a mistake', async () => {
  for (const argv of [
    ['discover', 'http://localhost:3000', '--runs', '3'],
    ['audit', 'http://localhost:3000', '--write'],
    ['discover', 'http://localhost:3000', '--depth', '9'],
    ['discover', 'http://localhost:3000', '--form-factor', 'tablet'],
    ['discover', 'http://localhost:3000', '--max-states', '0'],
    ['audit', 'http://localhost:3000', '--max-states', '5'],
    ['discover', 'a', 'b'],
  ]) {
    const { code, err } = await run(argv);
    assert.equal(code, 2, argv.join(' '));
    assert.match(err, /kanso --help/);
  }
});

test('with no page named and no serve: block, discover says what it needs', async () => {
  const { code, err } = await run(['discover']);
  assert.equal(code, 2);
  assert.match(err, /discover needs a URL or a directory/);
});

// The file kanso discover writes, gone wrong — edited by hand, merged badly —
// is what running it again is for: it must not stop the command that
// replaces it.
test('a generated file gone wrong is written again rather than refused', async () => {
  const cwd = project();
  mkdirSync(join(cwd, '.kanso'));
  writeFileSync(join(cwd, '.kanso', 'states.yml'), 'states:\n  - name: menu\n');
  const { code } = await run(['discover', 'http://localhost:3000', '--write'], { cwd });
  assert.equal(code, 0);
  assert.match(readFileSync(join(cwd, '.kanso', 'states.yml'), 'utf8'), /click: '#menu'/);
});
